name: 'branch-check'

on:
    pull_request:
        branches: [main]

jobs:
    check_branch:
        if: ${{ github.base_ref == 'main' }}
        runs-on: ubuntu-latest
        steps:
            - name: Stop merging
              run: |
                  echo 'Hi ${{ github.base_ref }}'
                  echo "ERROR: You can only merge to main from develop."
                  exit 1
