name: 'branch-check'

on:
    push:
        branches: [main]

jobs:
    check_branch:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - name: Stop merging
              run: |
                  echo github.base_ref
                  echo "ERROR: You can only merge to main from develop."
                  exit 1
