name: 'branch-check'

on:
    pull_request:
        branches: [main]

jobs:
    check_branch:
        runs-on: ubuntu-latest
        steps:
            - name: Check branch
              if: contains(fromJson('["master", "main"]'), github.base_ref) && github.head_ref != 'develop'
              steps:
                - name: Disable merging
                    run: |
                        echo github.base_ref
                        echo "ERROR: You can only merge to main from develop."
                        exit 1
