name: 'branch-check-second'

on: pull_request

jobs:
    check_branch_test:
        if: ${{ github.head_ref }}
        runs-on: ubuntu-latest
        steps:
            - name: Stop merging branches
              run: |
                  echo 'Hi ${{ github.head_ref }}'
                  echo "ERROR: You can only merge to main from develop copy."
                  exit 1
