name: 'branch-check'

on: pull_request

jobs:
    check_branch:
        if: ${{ github.base_ref == 'main' && github.head_ref  != 'develop' }}
        runs-on: ubuntu-latest
        steps:
            - name: Stop merging
              run: |
                  echo 'base_ref ${{ github.base_ref }}'
                  echo 'head_ref ${{ github.head_ref }}'
                  echo "ERROR: You can only merge to main from develop."
                  exit 1
